name: VSCode Ext Build & Release (LasecPlot)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Versão/Tag (ex.: v1.2.3 ou V1.2.3-RC5)"
        required: true
        type: string
      prerelease:
        description: "Marcar como pré-release?"
        required: false
        default: false
        type: boolean
      notes:
        description: "Notas da release (opcional)"
        required: false
        type: string

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    env:
      EXT_DIR: vscode
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
      OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
      npm_config_build_from_source: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            ${{ env.EXT_DIR }}/package-lock.json
            ${{ env.EXT_DIR }}/package.json

      - name: Dependências nativas
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends build-essential python3 make g++ libudev-dev jq

      - name: Verificações mínimas
        shell: bash
        run: |
          set -euxo pipefail
          test -d "${{ env.EXT_DIR }}"
          test -f "${{ env.EXT_DIR }}/package.json"

      - name: Normalizar versão e validar publisher
        id: ver
        shell: bash
        working-directory: ${{ env.EXT_DIR }}
        run: |
          set -euxo pipefail
          RAW="${{ inputs.version }}"
          RAW="${RAW//[[:space:]]/}"
          SANITIZED="${RAW#[vV]}"
          PR_FLAG="${{ inputs.prerelease }}"
          BASE="$SANITIZED"

          if [[ "$SANITIZED" =~ ^([0-9]+\.[0-9]+\.[0-9]+)-([A-Za-z]+)([0-9]+)$ ]]; then
            BASE="${BASH_REMATCH[1]}"
            PR_FLAG=true
          fi

          # version em package.json
          CUR=$(node -p "require('./package.json').version || ''")
          if [ "$CUR" != "$BASE" ]; then
            npm version "$BASE" --no-git-tag-version
          fi

          NAME=$(node -e "console.log(require('./package.json').name || '')")
          PUB=$(node -e "console.log(require('./package.json').publisher || '')")
          if [ -z "$PUB" ]; then
            echo "::error ::O campo 'publisher' está ausente no package.json. Defina o publisher (ex.: 'josuemoraisgh')."
            exit 1
          fi

          # arquivos básicos exigidos pelo Marketplace
          test -f README.md || { echo "::warning ::README.md ausente."; }
          test -f LICENSE || { echo "::warning ::LICENSE ausente."; }

          echo "SANITIZED_INPUT=$SANITIZED"   >> "$GITHUB_ENV"
          echo "BASE_VERSION=$BASE"           >> "$GITHUB_ENV"
          echo "IS_PRERELEASE=$PR_FLAG"       >> "$GITHUB_ENV"
          echo "EXT_NAME=$NAME"               >> "$GITHUB_ENV"
          echo "PUBLISHER=$PUB"               >> "$GITHUB_ENV"
          echo "VSIX_NAME=${PUB}.${NAME}-${SANITIZED}.vsix" >> "$GITHUB_ENV"

      - name: Criar .vscodeignore (se não existir)
        shell: bash
        working-directory: ${{ env.EXT_DIR }}
        run: |
          set -euxo pipefail
          if [ ! -f .vscodeignore ]; then
            cat > .vscodeignore <<'EOF'
# Ignorar dev e infra
.github/**
.vscode/**
.git/**
scripts/**
test/**
tests/**
coverage/**
node_modules/**
src/**
**/*.map

# Artefatos & cache
*.log
*.tgz
dist-*/**
tmp/**
.eslintcache
.prettierignore
.editorconfig
tsconfig.json
webpack.config.js
rollup.config.js
vite.config.*.ts
vite.config.*.js
pnpm-lock.yaml
yarn.lock

# Mantenha apenas o que é necessário no pacote:
# - out/ ou dist/ (código empacotado)
# - media/ (recursos do webview)
!out/**
!dist/**
!media/**
!package.json
!README.md
!CHANGELOG.md
!LICENSE
EOF
          fi

      - name: Instalar dependências
        shell: bash
        working-directory: ${{ env.EXT_DIR }}
        run: |
          set -euxo pipefail
          npm config set fund false
          npm config set audit false
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci --omit=optional || npm ci
          else
            npm install --no-audit --no-fund --omit=optional || npm install --no-audit --no-fund
          fi

      - name: Ajustar tsconfig e typings
        shell: bash
        working-directory: ${{ env.EXT_DIR }}
        run: |
          node <<'NODE'
          const fs = require('fs'); const p='tsconfig.json';
          let j={}; try{ j=JSON.parse(fs.readFileSync(p,'utf8')); }catch{}
          j.compilerOptions=j.compilerOptions||{};
          Object.assign(j.compilerOptions,{
            target:'ES2020', module:'commonjs', moduleResolution:'node',
            esModuleInterop:true, forceConsistentCasingInFileNames:true,
            skipLibCheck:true, skipDefaultLibCheck:true
          });
          const types=new Set([...(j.compilerOptions.types||[]),'node']); j.compilerOptions.types=[...types];
          if(!j.include) j.include=['src','out','typings'];
          fs.writeFileSync(p,JSON.stringify(j,null,2));
          console.log('tsconfig.json ok');
          NODE
          npm i -D @types/node@^20 --no-audit --no-fund

      - name: Build (se existir)
        working-directory: ${{ env.EXT_DIR }}
        run: npm run -s build || echo "Sem script de build"

      - name: Instalar CLIs (vsce/ovsx)
        run: npm i -g @vscode/vsce ovsx

      - name: Empacotar (.vsix)
        working-directory: ${{ env.EXT_DIR }}
        run: |
          set -euxo pipefail
          # Se files[] citar CHANGELOG.md inexistente, remove
          if jq -e '.files?|index("CHANGELOG.md")' package.json >/dev/null 2>&1 && [ ! -f CHANGELOG.md ]; then
            echo "::warning::Removendo CHANGELOG.md de files[] para evitar erro do vsce"
            jq 'del(.files[] | select(.=="CHANGELOG.md"))' package.json > package.tmp && mv package.tmp package.json
          fi
          vsce package -o "../${{ env.VSIX_NAME }}"

      - name: Upload artifact (.vsix)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VSIX_NAME }}
          path: ${{ env.VSIX_NAME }}
          if-no-files-found: error

      - name: Publicar no VS Code Marketplace (vsce)
        if: ${{ env.VSCE_PAT != '' }}
        working-directory: ${{ env.EXT_DIR }}
        env:
          VSCE_PAT: ${{ env.VSCE_PAT }}
        run: |
          set -euxo pipefail
          if [ "${IS_PRERELEASE}" = "true" ]; then
            vsce publish --pre-release --packagePath "../${VSIX_NAME}"
          else
            vsce publish --packagePath "../${VSIX_NAME}"
          fi

      - name: Publicar no Open VSX (opcional)
        if: ${{ env.OPEN_VSX_TOKEN != '' }}
        env:
          OPEN_VSX_TOKEN: ${{ env.OPEN_VSX_TOKEN }}
        run: |
          set -euxo pipefail
          if [ "${IS_PRERELEASE}" = "true" ]; then
            ovsx publish "${VSIX_NAME}" -p "${OPEN_VSX_TOKEN}" --pre-release
          else
            ovsx publish "${VSIX_NAME}" -p "${OPEN_VSX_TOKEN}"
          fi

      - name: Criar/empurrar tag
        shell: bash
        env:
          TAG_NAME: ${{ inputs.version }}
        run: |
          set -euxo pipefail
          git config --global --add safe.directory "$PWD"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git fetch --tags --force --prune
          git tag -a "${TAG_NAME}" -m "Release ${TAG_NAME}" || true
          git push origin "refs/tags/${TAG_NAME}" || true

      - name: Criar Release e anexar VSIX
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: LasecPlot VSCode ${{ inputs.version }}
          body: ${{ inputs.notes }}
          prerelease: ${{ env.IS_PRERELEASE }}
          target_commitish: ${{ github.sha }}
          files: ${{ env.VSIX_NAME }}
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
